export {
    ATTRIBUTE_HTMLLOAD,
    SELECTOR_HTMLLOAD,
    BREAKPOINT_SMALL_VALUE,
    BREAKPOINT_MEDIUM_VALUE,
    BREAKPOINT_LARGE_VALUE,
    BREAKPOINT_XLARGE_VALUE,
    BREAKPOINT_XXLARGE_VALUE,
    BREAKPOINT_XSMALL,
    BREAKPOINT_SMALL,
    BREAKPOINT_MEDIUM,
    BREAKPOINT_LARGE,
    BREAKPOINT_XLARGE,
    BREAKPOINT_XXLARGE,
    DICTIONARY_BREAKPOINT_TO_GALLERY_ITEM_ROW_COUNT
}

const ATTRIBUTE_HTMLLOAD = "js-html-load";
const SELECTOR_HTMLLOAD = `[${ATTRIBUTE_HTMLLOAD}]`
const BREAKPOINT_SMALL_VALUE = 576;
const BREAKPOINT_MEDIUM_VALUE = 768;
const BREAKPOINT_LARGE_VALUE = 992;
const BREAKPOINT_XLARGE_VALUE = 1200;
const BREAKPOINT_XXLARGE_VALUE = 1400;
const BREAKPOINT_XSMALL = "XS";
const BREAKPOINT_SMALL = "SM";
const BREAKPOINT_MEDIUM = "MD";
const BREAKPOINT_LARGE = "LG";
const BREAKPOINT_XLARGE = "XL";
const BREAKPOINT_XXLARGE = "XXL";
const DICTIONARY_BREAKPOINT_TO_GALLERY_ITEM_ROW_COUNT = {
    BREAKPOINT_SMALL:3,
    BREAKPOINT_MEDIUM:4,
    BREAKPOINT_LARGE:3
};